/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifdef __cplusplus
extern "C" {

JNIEXPORT void JNICALL Java_com_hugh_audiofun_FmodSound_playSound
  (JNIEnv *, jclass, jstring, jint);

JNIEXPORT void JNICALL Java_com_hugh_audiofun_FmodSound_resumeSound
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_hugh_audiofun_FmodSound_pauseSound
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_hugh_audiofun_FmodSound_stopSound
        (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_com_hugh_audiofun_FmodSound_isPlay
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_hugh_audiofun_FmodSound_saveSound
        (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
